program: src/train.py
method: bayes  # You can also use 'grid' or 'random'
metric:
  name: loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.001
  batch_size:
    values: [16, 32, 64]
  epochs:
    value: 30  # Fixed value for all sweeps