program: src/train.py
method: grid  # You can also use 'grid' or 'random'
metric:
  name: loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.001, 0.0001, 0.00001]
  batch_size:
    values: [16, 32, 64]
  epochs:
    value: 30  # Fixed value for all sweeps